name: Doucsaurus Build

on:
  push:
    branches: [ main ]
    paths:
      - docs/**
      - src/**
      - static/**
      - babel.config.js
      - docusaurus.config.js
      - sidebars.js
      - Dockerfile
  workflow_dispatch:

jobs:
  check_no_build:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Check Commit Type
      uses: gsactions/commit-message-checker@v1
      with:
        pattern: '^(?!.*\[no-build]).*$'
        flags: 'gms'
        error: 'Force no-build!'
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Login to DockerHub
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/archgryphon9362/teslabtapi:latest
