# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Doucsaurus Test Build

on:
  pull_request:
    branches: [main]
    paths:
      - docs/**
      - src/**
      - static/**
      - babel.config.js
      - docusaurus.config.js
      - sidebars.js
      - package.json

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: build
        run: |
          npm install
          yarn install
          yarn build
